In [ ]:
#data encoding>> converting categorical columns into numeric
#Nominal /OHE
#label and ordinal encoding
#Target guided ordinal encoding

In [2]:
#Nominal / OHE >>binary vector for each categories
# example : single , married ,saperated
# single [1,0,0]
# married [0,1,0]
# saperated[0,0,1]

import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df=pd.DataFrame({'status':['single','married','saperated','single','single','married','married']})
df

status
0     single
1    married
2  saperated
3     single
4     single
5    married
6    married

In [11]:
encoder=OneHotEncoder()
encoded=encoder.fit_transform(df[['status']]).toarray()
encoder.get_feature_names_out()

array(['status_married', 'status_saperated', 'status_single'],
      dtype=object)

In [12]:
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())
encoder_df

status_married  status_saperated  status_single
0             0.0               0.0            1.0
1             1.0               0.0            0.0
2             0.0               1.0            0.0
3             0.0               0.0            1.0
4             0.0               0.0            1.0
5             1.0               0.0            0.0
6             1.0               0.0            0.0

In [13]:
pd.concat([df,encoder_df],axis=1)

status  status_married  status_saperated  status_single
0     single             0.0               0.0            1.0
1    married             1.0               0.0            0.0
2  saperated             0.0               1.0            0.0
3     single             0.0               0.0            1.0
4     single             0.0               0.0            1.0
5    married             1.0               0.0            0.0
6    married             1.0               0.0            0.0

now we can remove any one column from an the result will be still same eg if we remove status_single column then in row 0 the status_married = 0 and status_saperated is also 0 its simply indicates that status_single is 1 so in conclusion its n-1 i.e we can remove any column and the result will still be the same

In [23]:
lst=['single','married','saperated','single','single','married','married']
dummies = pd.get_dummies(lst,dtype=int)
dummies

married  saperated  single
0        0          0       1
1        1          0       0
2        0          1       0
3        0          0       1
4        0          0       1
5        1          0       0
6        1          0       0

In [25]:
pd.concat([pd.DataFrame(lst),dummies],axis=1)

0  married  saperated  single
0     single        0          0       1
1    married        1          0       0
2  saperated        0          1       0
3     single        0          0       1
4     single        0          0       1
5    married        1          0       0
6    married        1          0       0

In [26]:
#label encoding>>Assigns unique label to categories
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()
label_encoder.fit_transform(df['status'])


array([2, 0, 1, 2, 2, 0, 0])

In [27]:
# if new data comes
label_encoder.transform([['single']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([2])

In [32]:
#ordinal encoding
#High school : 1
#Graduate : 2
#pd:3
#Phd:4
from sklearn.preprocessing import OrdinalEncoder
df=pd.DataFrame({'qualification':['HS','GR','PG','PHD','HS','HS','PHD','PG']})
df

qualification
0            HS
1            GR
2            PG
3           PHD
4            HS
5            HS
6           PHD
7            PG

In [33]:
encoder=OrdinalEncoder(categories=[['HS','GR','PG','PHD']])
encoder.fit_transform(df[['qualification']])

array([[0.],
       [1.],
       [2.],
       [3.],
       [0.],
       [0.],
       [3.],
       [2.]])

In [34]:
#new data
encoder.transform([['PG']])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[2.]])

In [35]:
#Target guided ordinal encoding
#relationship with target variables
#A lot of unique categories

#Replace the category with the mean and median of respective group target

df = pd.DataFrame({'time':['lunch','breakfast','dinner','lunch','breakfast','dinner','lunch','breakfast','dinner'],'total_bill':[120,130,90,125,150,190,160,180,189]})
df

time  total_bill
0      lunch         120
1  breakfast         130
2     dinner          90
3      lunch         125
4  breakfast         150
5     dinner         190
6      lunch         160
7  breakfast         180
8     dinner         189

In [41]:
mean_price =df.groupby('time')['total_bill'].mean().to_dict()
mean_price

{'breakfast': 153.33333333333334, 'dinner': 156.33333333333334, 'lunch': 135.0}

In [43]:
df['time_encoded']=df['time'].map(mean_price)
df

time  total_bill  time_encoded
0      lunch         120    135.000000
1  breakfast         130    153.333333
2     dinner          90    156.333333
3      lunch         125    135.000000
4  breakfast         150    153.333333
5     dinner         190    156.333333
6      lunch         160    135.000000
7  breakfast         180    153.333333
8     dinner         189    156.333333